# Generated by Django 5.2.4 on 2025-08-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_subject_grade_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'student__name'],
                'indexes': [models.Index(fields=['student', 'date'], name='attendance__student_76a8d7_idx'), models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['present'], name='attendance__present_b77c6b_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
