# Generated by Django 5.2.4 on 2025-07-18 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('grade_level', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject_selected',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='classes',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.class'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects_selected',
            field=models.ManyToManyField(blank=True, to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='classes',
            field=models.ManyToManyField(blank=True, to='accounts.class'),
        ),
    ]
