# Generated by Django 5.2.4 on 2025-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_class_subject_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_levels',
            field=models.CharField(default='9,10,11,12', max_length=20),
        ),
    ]
