# Generated by Django 5.2.4 on 2025-08-03 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_subject_grade_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.class')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-exam_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='marks.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
                'ordering': ['-exam__exam_date', 'subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['student_class', '-exam_date'], name='marks_exam_student_1d56e9_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_date'], name='marks_exam_exam_da_9d93f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'exam_date', 'student_class')},
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['student', 'exam'], name='marks_marks_student_68c147_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['exam', 'subject'], name='marks_marks_exam_id_e0e822_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['student', 'subject'], name='marks_marks_student_e4bf4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'exam', 'subject')},
        ),
    ]
