# Generated by Django 5.2.4 on 2025-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subject_grade_levels'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['student_class', 'name'], name='marks_exam_student_2b66b5_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['-exam_date', 'name'], name='marks_exam_exam_da_37d7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['exam', 'student'], name='marks_marks_exam_id_deaaab_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['created_at'], name='marks_marks_created_67a9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['updated_at'], name='marks_marks_updated_15a73c_idx'),
        ),
    ]
