# Generated by Django 5.2.4 on 2025-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admissioninquiry',
            index=models.Index(fields=['status', '-created_at'], name='students_ad_status_bc1f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioninquiry',
            index=models.Index(fields=['email'], name='students_ad_email_539dff_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioninquiry',
            index=models.Index(fields=['created_at'], name='students_ad_created_cb85c7_idx'),
        ),
    ]
