# Generated by Django 5.2.4 on 2025-08-02 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_class_subject_alter_faculty_options_and_more'),
        ('students', '0002_admissioninquiry_students_ad_status_bc1f3a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final Exam'), ('assignment', 'Assignment'), ('project', 'Project')], max_length=20)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'ordering': ['-exam_date', 'subject__name'],
                'indexes': [models.Index(fields=['student', 'subject'], name='students_st_student_5a31e7_idx'), models.Index(fields=['exam_date'], name='students_st_exam_da_e3ccce_idx'), models.Index(fields=['exam_type'], name='students_st_exam_ty_3cda88_idx')],
                'unique_together': {('student', 'subject', 'exam_type', 'exam_date')},
            },
        ),
    ]
