# Generated by Django 5.2.4 on 2025-08-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='accounts.adminuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='accounts.student')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'admin')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('system', 'System')], max_length=10)),
                ('sender_id', models.IntegerField()),
                ('sender_name', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('system', 'System')], default='text', max_length=10)),
                ('content', models.TextField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('system', 'System')], max_length=10)),
                ('recipient_id', models.IntegerField()),
                ('unread_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chatroom')),
            ],
            options={
                'unique_together': {('room', 'recipient_type', 'recipient_id')},
            },
        ),
    ]
