# Generated by Django 5.2.4 on 2025-08-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminuser'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='recipient_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('principal', 'Principal')], default='admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('faculty', 'Faculty'), ('principal', 'Principal'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatnotification',
            name='recipient_type',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('faculty', 'Faculty'), ('principal', 'Principal'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('student', 'recipient_type')},
        ),
    ]
