# Generated by Django 5.2.4 on 2025-08-02 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_class_subject_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('recommended_for_grade', models.IntegerField()),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendations', to='accounts.subject')),
            ],
            options={
                'verbose_name': 'Book Recommendation',
                'verbose_name_plural': 'Book Recommendations',
                'ordering': ['subject__name', 'title'],
                'indexes': [models.Index(fields=['subject', 'recommended_for_grade'], name='recommendat_subject_64bc71_idx'), models.Index(fields=['is_available'], name='recommendat_is_avai_540a37_idx'), models.Index(fields=['title'], name='recommendat_title_7e90b0_idx')],
            },
        ),
    ]
